import { CloudArchitecture } from '../types';

export function generatePythonIaC(arch: CloudArchitecture): string {
  const { provider, resources } = arch;
  
  let code = `import pulumi\n`;
  if (provider === 'aws') code += `import pulumi_aws as aws\n\n`;
  if (provider === 'gcp') code += `import pulumi_gcp as gcp\n\n`;
  if (provider === 'azure') code += `import pulumi_azure as azure\n\n`;

  code += `# Cloud Architecture: ${arch.name}\n`;
  code += `# Generated by CloudArch Dashboard\n\n`;

  // Filter VPCs
  const vpcs = resources.filter(r => r.type === 'vpc');
  vpcs.forEach(vpc => {
    code += `vpc = aws.ec2.Vpc("${vpc.name}",\n`;
    code += `    cidr_block="${vpc.config.cidr || '10.0.0.0/16'}",\n`;
    code += `    enable_dns_hostnames=True,\n`;
    code += `    tags={"Name": "${vpc.name}"})\n\n`;
  });

  // Subnets
  const subnets = resources.filter(r => r.type === 'subnet');
  subnets.forEach((s, idx) => {
    code += `subnet_${idx} = aws.ec2.Subnet("${s.name}",\n`;
    code += `    vpc_id=vpc.id,\n`;
    code += `    cidr_block="${s.config.cidr || `10.0.${idx}.0/24`}",\n`;
    code += `    availability_zone="${s.config.az || 'us-east-1a'}",\n`;
    code += `    tags={"Name": "${s.name}"})\n\n`;
  });

  // Instances
  const instances = resources.filter(r => r.type === 'instance');
  instances.forEach((inst, idx) => {
    code += `instance_${idx} = aws.ec2.Instance("${inst.name}",\n`;
    code += `    instance_type="${inst.config.size || 't3.micro'}",\n`;
    code += `    subnet_id=subnet_0.id,\n`;
    code += `    ami="ami-0c55b159cbfafe1f0", # Amazon Linux 2\n`;
    code += `    tags={"Name": "${inst.name}"})\n\n`;
  });

  // Databases
  const databases = resources.filter(r => r.type === 'database');
  databases.forEach((db, idx) => {
    code += `db_${idx} = aws.rds.Instance("${db.name}",\n`;
    code += `    instance_class="db.t3.micro",\n`;
    code += `    engine="postgres",\n`;
    code += `    allocated_storage=20,\n`;
    code += `    db_name="${db.name.replace(/-/g, '_')}",\n`;
    code += `    skip_final_snapshot=True)\n\n`;
  });

  code += `pulumi.export("vpc_id", vpc.id)\n`;
  
  return code;
}
